version: '2'
services:
  web:
    image: odoo:12
    ports:
      - "8069:8069"
    volumes:
     - ./extra:/mnt/extra-addons
     - ./config:/etc/odoo
     - ./data:/var/lib/odoo
    command: odoo -u all -d odoo