- hosts: monitor
  become: yes
  gather_facts: true
  tasks:
    - name: Install dependencies
      apt: pkg="{{ item }}" update_cache=yes state=latest force_apt_get=yes
      loop: ['apt-transport-https', 'gnupg2', 'software-properties-common' ]
    - name: Add Influxdb apt key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present
    - name: Add Influxdb repository
      apt_repository:
        repo: 'deb https://repos.influxdata.com/ubuntu focal stable'
        state: present
        update_cache: true
    - name: Install InfluxDB
      package:
        name: influxdb
        state: present
    - name: Ensure Telegraf is started and enabled at boot
      service:
        name: influxdb
        state: started
        enabled: yes
    - name: Add Grafana apt key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
    - name: Add Grafana repository
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present
        update_cache: true
    - name: Install Grafana
      package:
        name: grafana
        state: present
    - name: Ensure Grafana is started and enabled at boot
      service:
        name: grafana-server
        state: started
        enabled: yes
    - name: Create dashboard directory
      file:
        path: /var/lib/grafana/dashboards
        state: directory
    - name: Copy DataSource configuration.
      template:
        src: "templates/odoo-ds.yaml.j2"
        dest: "/etc/grafana/provisioning/datasources/odoo-ds.yaml"
        owner: root
        group: root
        mode: 0644
      notify: Restart Grafana
    - name: Copy Dashboards configuration
      copy:
        src: templates/odoo-dashb.yaml
        dest: /etc/grafana/provisioning/dashboards/odoo-dashb.yaml
        owner: root
        group: root
        mode: 0644
      notify: Restart Grafana
    - name: Copy Host Dashboards
      copy:
        src: templates/host-db.json
        dest: /var/lib/grafana/dashboards/host-db.json
        owner: root
        group: root
        mode: 0644
      notify: Restart Grafana
    - name: Copy Host Dashboards
      copy:
        src: templates/host-uptime.json
        dest: /var/lib/grafana/dashboards/host-uptime.json
        owner: root
        group: root
        mode: 0644
      notify: Restart Grafana
  handlers:
    - name: Restart Grafana
      service:
        name: grafana-server
        state: restarted
